name: Build

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies and build db
        run: |
          make install
          make migrate
          make build-db
      - name: Upload SQLite dump as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pokeapi.sqlite3
          path: db.sqlite3
