name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Start pokeapi (docker)
        run: |
          docker compose -f docker-compose.yml -f docker-compose-dev.yml up -d
          make docker-migrate
          make docker-build-db
      - name: Dump PG db
        run: docker compose exec -T -u postgres db sh -c "cd /tmp && pg_dump -h localhost -Fc -U ash -N 'hdb_*' pokeapi > pokeapi.pgdump"
      - name: Copy PG dump
        run: docker compose cp db:/tmp/pokeapi.pgdump ./
      - name: Upload PG dump as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pokeapi-pgdump
          path: pokeapi.pgdump
      - name: Dump SQLite db
        run: cp db.sqlite3 ./
      - name: Upload SQLite dump as artifact
        uses: actions/upload-artifact@v3
        with:
          name: db-sqlite3
          path: db.sqlite3
